<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Aditi" ignored="0" name="Default test" tests="7" failures="1" timestamp="06 Feb 2017 10:40:01 GMT" time="129.147" errors="0">
  <testcase name="executeTestCase" time="30.938" classname="com.test.automation.testStartup.TestLauncher"/>
  <testcase name="executeTestCase" time="6.726" classname="com.test.automation.testStartup.TestLauncher"/>
  <testcase name="executeTestCase" time="24.527" classname="com.test.automation.testStartup.TestLauncher"/>
  <testcase name="executeTestCase" time="58.828" classname="com.test.automation.testStartup.TestLauncher">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="2">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 2
	at com.test.automation.executionEngine.TestCaseDriver.executeTestSteps(TestCaseDriver.java:60)
	at com.test.automation.testStartup.TestLauncher.executeTestCase(TestLauncher.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- executeTestCase -->
  <testcase name="executeTestCase" time="2.738" classname="com.test.automation.testStartup.TestLauncher">
    <skipped/>
  </testcase> <!-- executeTestCase -->
  <testcase name="executeTestCase" time="2.824" classname="com.test.automation.testStartup.TestLauncher">
    <skipped/>
  </testcase> <!-- executeTestCase -->
  <testcase name="executeTestCase" time="2.397" classname="com.test.automation.testStartup.TestLauncher">
    <skipped/>
  </testcase> <!-- executeTestCase -->
</testsuite> <!-- Default test -->
